<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE List [
     <!ELEMENT FunctionalBlock (Code+, Version+, DatePublication+, Nom+, Zones+, XmlLabel+, Description+, CardinaliteMinimum+, CardinaliteMaximum+, NrBlocLie+, BlocLie+, Presence+, LimitationsSupplementaires+, Anomalie+)>
     <!ELEMENT List (FunctionalBlock+)>
     <!ELEMENT Code (#PCDATA)>
     <!ELEMENT Version (#PCDATA)>
     <!ELEMENT DatePublication (#PCDATA)>
     <!ELEMENT Nom (#PCDATA)>
     <!ELEMENT Zones (#PCDATA)>
     <!ELEMENT XmlLabel (#PCDATA)>
     <!ELEMENT Description (#PCDATA)>
     <!ELEMENT CardinaliteMinimum (#PCDATA)>
     <!ELEMENT CardinaliteMaximum (#PCDATA)>
     <!ELEMENT NrBlocLie (#PCDATA)>
     <!ELEMENT BlocLie (#PCDATA)>
     <!ELEMENT Presence (#PCDATA)>
     <!ELEMENT LimitationsSupplementaires (#PCDATA)>
     <!ELEMENT Anomalie (CodeAnomalie+,IntituleAnomalie+,GraviteAnomalie+)>
     <!ELEMENT CodeAnomalie (#PCDATA)>
     <!ELEMENT IntituleAnomalie (#PCDATA)>
     <!ELEMENT GraviteAnomalie (#PCDATA)>
]>
<List>
     <FunctionalBlock>
          <Code>90578</Code>
          <Version>2022/3</Version>
          <DatePublication>30/08/2022</DatePublication>
          <Nom>Activation - Informations</Nom>
          <Zones>01191 - DATE DE DÉBUT DISPENSE DE PRESTATIONS</Zones>
          <Zones>01192 - DATE DE DÉBUT SITUATION DE FORMATION</Zones>
          <Zones>01193 - SITUATION DE FORMATION</Zones>
          <XmlLabel>ActivationInformation</XmlLabel>
          <Description>Bloc fonctionnel contenant les données permettant de calculer la cotisation
               d'activation.</Description>
          <CardinaliteMinimum>0</CardinaliteMinimum>
          <CardinaliteMaximum>1</CardinaliteMaximum>
          <NrBlocLie></NrBlocLie>
          <BlocLie></BlocLie>
          <Presence>Cardinalité 0 si la zone « Notion de dispense de prestations » (00826) est non
               présente ou  2 dans tous les blocs Occupation – Informations (90313). Cardinalité 1
               si la zone « Notion de dispense de prestations » (00826) = 2 dans au moins 1 bloc
               Occupation-Informations (90313).</Presence>
          <LimitationsSupplementaires></LimitationsSupplementaires>
          <Anomalie>
               <CodeAnomalie>90578-001</CodeAnomalie>
               <IntituleAnomalie>Non présent</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>90578-035</CodeAnomalie>
               <IntituleAnomalie>Incompatibilité trimestre - catégorie employeur</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>90578-030</CodeAnomalie>
               <IntituleAnomalie>Incompatibilité code travailleur</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>90578-053</CodeAnomalie>
               <IntituleAnomalie>Pas d'application</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>90578-090</CodeAnomalie>
               <IntituleAnomalie>Erreur de cardinalité</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>90578-091</CodeAnomalie>
               <IntituleAnomalie>Erreur de séquence</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>90578-146</CodeAnomalie>
               <IntituleAnomalie>Non admis</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
     </FunctionalBlock>
     <FunctionalBlock>
          <Code>90001</Code>
          <Version>2022/3</Version>
          <DatePublication>30/08/2022</DatePublication>
          <Nom>Cotisation due pour la ligne travailleur</Nom>
          <Zones>00082 - CODE TRAVAILLEUR COTISATION</Zones>
          <Zones>00083 - TYPE DE COTISATION</Zones>
          <Zones>00084 - BASE DE CALCUL DE LA COTISATION</Zones>
          <Zones>00085 - MONTANT DE LA COTISATION</Zones>
          <Zones>00896 - DATE PREMIÈRE EMBAUCHE</Zones>
          <XmlLabel>WorkerContribution</XmlLabel>
          <Description>Bloc fonctionnel permettant de déclarer les cotisations dues pour une ligne
               travailleur.</Description>
          <CardinaliteMinimum>0</CardinaliteMinimum>
          <CardinaliteMaximum>*</CardinaliteMaximum>
          <NrBlocLie></NrBlocLie>
          <BlocLie></BlocLie>
          <Presence>Cardinalité 0 ... * si la ligne travailleur concerne un code travailleur
               cotisation ordinaire (voir annexe 2). Cardinalité 1 ou 2 si la ligne travailleur
               concerne un code travailleur cotisation Fedris (voir annexe 2). Cardinalité 0 ou 1 si
               la ligne travailleur concerne un code travailleur cotisation spéciale étudiant.
               Cardinalité 0 sinon.</Presence>
          <LimitationsSupplementaires>Une cotisation donnée (une combinaison code travailleur
               cotisation / type de cotisation) ne peut se retrouver qu'une seule fois par ligne
               travailleur.</LimitationsSupplementaires>
          <Anomalie>
               <CodeAnomalie>90001-001</CodeAnomalie>
               <IntituleAnomalie>Non présent</IntituleAnomalie>
               <GraviteAnomalie>P</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>90001-006</CodeAnomalie>
               <IntituleAnomalie>Trop d'occurrences avec les mêmes identifiants</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>90001-030</CodeAnomalie>
               <IntituleAnomalie>Incompatibilité code travailleur</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>90001-091</CodeAnomalie>
               <IntituleAnomalie>Erreur de séquence</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>90001-146</CodeAnomalie>
               <IntituleAnomalie>Non admis</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>90001-212</CodeAnomalie>
               <IntituleAnomalie>Incompatibilité avec le statut du travailleur</IntituleAnomalie>
               <GraviteAnomalie>P</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>90001-316</CodeAnomalie>
               <IntituleAnomalie>Type cotisation - combinaison non autorisé</IntituleAnomalie>
               <GraviteAnomalie>P</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>90001-476</CodeAnomalie>
               <IntituleAnomalie>Cotisation spéciale sur les indemnités de rupture non présente</IntituleAnomalie>
               <GraviteAnomalie>NP</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>90001-480</CodeAnomalie>
               <IntituleAnomalie>Cotisation pension du secteur public non présente</IntituleAnomalie>
               <GraviteAnomalie>P</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>90001-519</CodeAnomalie>
               <IntituleAnomalie>Pensionné avant le 01/01/2016</IntituleAnomalie>
               <GraviteAnomalie>W</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>90001-520</CodeAnomalie>
               <IntituleAnomalie>Pensionné après le 31/12/2015</IntituleAnomalie>
               <GraviteAnomalie>NP</GraviteAnomalie>
          </Anomalie>
     </FunctionalBlock>
     <FunctionalBlock>
          <Code>90002</Code>
          <Version>2022/3</Version>
          <DatePublication>30/08/2022</DatePublication>
          <Nom>Cotisation non liée à une personne physique</Nom>
          <Zones>00019 - CATÉGORIE DE L'EMPLOYEUR POUR LAQUELLE UNE COTISATION NON LIÉE À UNE
               PERSONNE PHYSIQUE EST DUE</Zones>
          <Zones>00020 - CODE TRAVAILLEUR POUR UNE COTISATION QUI N'EST PAS LIÉE À UNE PERSONNE
               PHYSIQUE</Zones>
          <Zones>00021 - BASE DE CALCUL DE LA COTISATION NON LIÉE À UNE PERSONNE PHYSIQUE</Zones>
          <Zones>00022 - MONTANT DE LA COTISATION NON LIÉE À UNE PERSONNE PHYSIQUE</Zones>
          <XmlLabel>ContributionUnrelatedToNP</XmlLabel>
          <Description>Bloc fonctionnel permettant de déclarer les cotisations non liées à une
               personne physique dues par l'employeur.</Description>
          <CardinaliteMinimum>0</CardinaliteMinimum>
          <CardinaliteMaximum>*</CardinaliteMaximum>
          <NrBlocLie></NrBlocLie>
          <BlocLie></BlocLie>
          <Presence>Cardinalité 0 si aucune cotisation non liée à une personne physique n'est due.
               Cardinalité 1 ... * si au moins une cotisation non liée à une personne physique est
               due.</Presence>
          <LimitationsSupplementaires>Une cotisation donnée (une combinaison catégorie / code
               travailleur pour laquelle une cotisation non liée à une personne physique est due) ne
               peut se retrouver qu'une seule fois par déclaration.</LimitationsSupplementaires>
          <Anomalie>
               <CodeAnomalie>90002-001</CodeAnomalie>
               <IntituleAnomalie>Non présent</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>90002-006</CodeAnomalie>
               <IntituleAnomalie>Trop d'occurrences avec les mêmes identifiants</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>90002-091</CodeAnomalie>
               <IntituleAnomalie>Erreur de séquence</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>90002-146</CodeAnomalie>
               <IntituleAnomalie>Non admis</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>90002-426</CodeAnomalie>
               <IntituleAnomalie>Cotisation pension extra-légale (plan de pension sectoriel ou
                    d'entreprise) non présente</IntituleAnomalie>
               <GraviteAnomalie>P</GraviteAnomalie>
          </Anomalie>
     </FunctionalBlock>
     <FunctionalBlock>
          <Code>90003</Code>
          <Version>2022/3</Version>
          <DatePublication>30/08/2022</DatePublication>
          <Nom>Cotisation travailleur étudiant</Nom>
          <Zones>00076 - RÉMUNÉRATION ÉTUDIANT</Zones>
          <Zones>00077 - COTISATION ÉTUDIANT</Zones>
          <Zones>00078 - NOMBRE DE JOURS ÉTUDIANT</Zones>
          <Zones>01158 - NOMBRE D'HEURES ÉTUDIANT</Zones>
          <Zones>00042 - NUMÉRO D'IDENTIFICATION DE L'UNITÉ LOCALE</Zones>
          <XmlLabel>StudentContribution</XmlLabel>
          <Description>Bloc fonctionnel permettant de déclarer la cotisation de solidarité due pour
               un étudiant.</Description>
          <CardinaliteMinimum>0</CardinaliteMinimum>
          <CardinaliteMaximum>1</CardinaliteMaximum>
          <NrBlocLie></NrBlocLie>
          <BlocLie></BlocLie>
          <Presence>Cardinalité 0 si la ligne travailleur ne concerne pas un travailleur étudiant
               (voir annexe 2). Cardinalité 1 (indispensable) si la ligne travailleur concerne un
               travailleur étudiant (voir annexe 2).</Presence>
          <LimitationsSupplementaires></LimitationsSupplementaires>
          <Anomalie>
               <CodeAnomalie>90003-025</CodeAnomalie>
               <IntituleAnomalie>Incompatibilité catégorie employeur</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>90003-030</CodeAnomalie>
               <IntituleAnomalie>Incompatibilité code travailleur</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>90003-090</CodeAnomalie>
               <IntituleAnomalie>Erreur de cardinalité</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>90003-091</CodeAnomalie>
               <IntituleAnomalie>Erreur de séquence</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>90003-146</CodeAnomalie>
               <IntituleAnomalie>Non admis</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
     </FunctionalBlock>
     <FunctionalBlock>
          <Code>90042</Code>
          <Version>2022/3</Version>
          <DatePublication>30/08/2022</DatePublication>
          <Nom>Cotisation travailleur prépensionné</Nom>
          <Zones>00079 - CODE COTISATION PRÉPENSION</Zones>
          <Zones>00080 - NOMBRE DE MOIS PRÉPENSION</Zones>
          <Zones>00081 - COTISATION PRÉPENSION</Zones>
          <XmlLabel>EarlyRetirementContribution</XmlLabel>
          <Description>Bloc fonctionnel permettant de déclarer les cotisations dues pour un
               travailleur prépensionné.</Description>
          <CardinaliteMinimum>0</CardinaliteMinimum>
          <CardinaliteMaximum>2</CardinaliteMaximum>
          <NrBlocLie></NrBlocLie>
          <BlocLie></BlocLie>
          <Presence>Cardinalité 0 si la ligne travailleur ne concerne pas un travailleur
               prépensionné ou, à partir des déclarations du 2/2010, si la ligne travailleur
               concerne un travailleur prépensionné (voir annexe 2). Cardinalité 1 ... 2 jusqu'aux
               déclarations du 1/2010, si la ligne travailleur concerne un travailleur prépensionné
               (voir annexe 2).</Presence>
          <LimitationsSupplementaires>Une cotisation travailleur prépensionné donnée (un code
               cotisation prépension) ne peut se retrouver qu'une seule fois par ligne travailleur.</LimitationsSupplementaires>
          <Anomalie>
               <CodeAnomalie>90042-006</CodeAnomalie>
               <IntituleAnomalie>Trop d'occurrences avec les mêmes identifiants</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>90042-025</CodeAnomalie>
               <IntituleAnomalie>Incompatibilité catégorie employeur</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>90042-030</CodeAnomalie>
               <IntituleAnomalie>Incompatibilité code travailleur</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>90042-090</CodeAnomalie>
               <IntituleAnomalie>Erreur de cardinalité</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>90042-091</CodeAnomalie>
               <IntituleAnomalie>Erreur de séquence</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>90042-146</CodeAnomalie>
               <IntituleAnomalie>Non admis</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
     </FunctionalBlock>
     <FunctionalBlock>
          <Code>90005</Code>
          <Version>2022/3</Version>
          <DatePublication>30/08/2022</DatePublication>
          <Nom>Cotisation travailleur statutaire licencié</Nom>
          <Zones>00071 - RÉMUNÉRATION BRUTE DE RÉFÉRENCE</Zones>
          <Zones>00072 - COTISATION RÉMUNÉRATION BRUTE DE RÉFÉRENCE</Zones>
          <Zones>00073 - NOMBRE DE JOURS DE RÉFÉRENCE</Zones>
          <Zones>00127 - DATE DE DÉBUT DE PÉRIODE DE L'ASSUJETTISSEMENT</Zones>
          <Zones>00129 - DATE DE FIN DE PÉRIODE DE L'ASSUJETTISSEMENT</Zones>
          <XmlLabel>DismissedStatutoryWorkerContribution</XmlLabel>
          <Description>Bloc fonctionnel permettant de déclarer les cotisations dues pour un
               travailleur statutaire licencié.</Description>
          <CardinaliteMinimum>0</CardinaliteMinimum>
          <CardinaliteMaximum>1</CardinaliteMaximum>
          <NrBlocLie></NrBlocLie>
          <BlocLie></BlocLie>
          <Presence>Cardinalité 0 si la ligne travailleur ne concerne pas un travailleur statutaire
               licencié (voir annexe 2). Cardinalité 1 (indispensable) si la ligne travailleur
               concerne un travailleur statutaire licencié (voir annexe 2).</Presence>
          <LimitationsSupplementaires></LimitationsSupplementaires>
          <Anomalie>
               <CodeAnomalie>90005-025</CodeAnomalie>
               <IntituleAnomalie>Incompatibilité catégorie employeur</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>90005-030</CodeAnomalie>
               <IntituleAnomalie>Incompatibilité code travailleur</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>90005-090</CodeAnomalie>
               <IntituleAnomalie>Erreur de cardinalité</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>90005-091</CodeAnomalie>
               <IntituleAnomalie>Erreur de séquence</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>90005-146</CodeAnomalie>
               <IntituleAnomalie>Non admis</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
     </FunctionalBlock>
     <FunctionalBlock>
          <Code>90007</Code>
          <Version>2022/3</Version>
          <DatePublication>30/08/2022</DatePublication>
          <Nom>Déclaration employeur</Nom>
          <Zones>00013 - ANNÉE - TRIMESTRE</Zones>
          <Zones>00011 - NUMÉRO ONSS</Zones>
          <Zones>00012 - NOTION CURATELLE</Zones>
          <Zones>00014 - NUMÉRO D'ENTREPRISE</Zones>
          <Zones>00015 - MONTANT NET À PAYER</Zones>
          <Zones>00016 - CONVERSION EN RÉGIME 5</Zones>
          <Zones>00017 - DATE DE DÉBUT DES VACANCES</Zones>
          <XmlLabel>EmployerDeclaration</XmlLabel>
          <Description>Bloc fonctionnel permettant de déclarer les données de la déclaration.</Description>
          <CardinaliteMinimum>1</CardinaliteMinimum>
          <CardinaliteMaximum>1</CardinaliteMaximum>
          <NrBlocLie>90017</NrBlocLie>
          <NrBlocLie>90294</NrBlocLie>
          <NrBlocLie>90002</NrBlocLie>
          <BlocLie>90017 - Personne physique</BlocLie>
          <BlocLie>90294 - Véhicule de société</BlocLie>
          <BlocLie>90002 - Cotisation non liée à une personne physique</BlocLie>
          <Presence>Indispensable</Presence>
          <LimitationsSupplementaires></LimitationsSupplementaires>
          <Anomalie>
               <CodeAnomalie>90007-006</CodeAnomalie>
               <IntituleAnomalie>Trop d'occurrences avec les mêmes identifiants</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>90007-090</CodeAnomalie>
               <IntituleAnomalie>Erreur de cardinalité</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>90007-091</CodeAnomalie>
               <IntituleAnomalie>Erreur de séquence</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>90007-134</CodeAnomalie>
               <IntituleAnomalie>Pas de données</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>90007-146</CodeAnomalie>
               <IntituleAnomalie>Non admis</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>90007-165</CodeAnomalie>
               <IntituleAnomalie>Déclaration mixte - catégorie employeur 021</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>90007-151</CodeAnomalie>
               <IntituleAnomalie>Pas identifiable</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>90007-262</CodeAnomalie>
               <IntituleAnomalie>Plus de travailleurs déclarés en DmfA qu'en DIMONA</IntituleAnomalie>
               <GraviteAnomalie>NP</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>90007-263</CodeAnomalie>
               <IntituleAnomalie>Moins de travailleurs déclarés en DmfA qu'en DIMONA</IntituleAnomalie>
               <GraviteAnomalie>NP</GraviteAnomalie>
          </Anomalie>
     </FunctionalBlock>
     <FunctionalBlock>
          <Code>90110</Code>
          <Version>2022/3</Version>
          <DatePublication>30/08/2022</DatePublication>
          <Nom>Déduction ligne travailleur</Nom>
          <Zones>00086 - CODE DÉDUCTION</Zones>
          <Zones>00088 - BASE DE CALCUL DE LA DÉDUCTION</Zones>
          <Zones>00089 - MONTANT DE LA DÉDUCTION</Zones>
          <Zones>00090 - DATE DE DÉBUT DU DROIT À LA DÉDUCTION</Zones>
          <Zones>00091 - NOMBRE DE MOIS FRAIS DE GESTION SSA</Zones>
          <Zones>00092 - NUMÉRO D'IDENTIFICATION DE LA SÉCURITÉ SOCIALE - NISS DE LA PERSONNE
               REMPLACÉE</Zones>
          <Zones>00093 - NUMÉRO D'IDENTIFICATION DE LA SÉCURITÉ SOCIALE - NISS DE LA PERSONNE QUI A
               OUVERT LE DROIT À LA DÉDUCTION</Zones>
          <Zones>00094 - ORIGINE DE L'ATTESTATION</Zones>
          <XmlLabel>WorkerDeduction</XmlLabel>
          <Description>Bloc fonctionnel permettant de déclarer les déductions demandées pour une
               ligne travailleur.</Description>
          <CardinaliteMinimum>0</CardinaliteMinimum>
          <CardinaliteMaximum>*</CardinaliteMaximum>
          <NrBlocLie>90108</NrBlocLie>
          <BlocLie>90108 - Détail données déduction ligne travailleur</BlocLie>
          <Presence>Cardinalité 0 si aucune déduction ligne travailleur n'est demandée. Cardinalité
               1 ... * si la ligne travailleur concerne un code travailleur cotisation ordinaire
               (voir annexe 2) et qu'une déduction ligne travailleur (voir annexe 4) est demandée.</Presence>
          <LimitationsSupplementaires>Une déduction ligne travailleur donnée (un code déduction) ne
               peut se retrouver qu'une seule fois par ligne travailleur.</LimitationsSupplementaires>
          <Anomalie>
               <CodeAnomalie>90110-006</CodeAnomalie>
               <IntituleAnomalie>Trop d'occurrences avec les mêmes identifiants</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>90110-025</CodeAnomalie>
               <IntituleAnomalie>Incompatibilité catégorie employeur</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>90110-030</CodeAnomalie>
               <IntituleAnomalie>Incompatibilité code travailleur</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>90110-091</CodeAnomalie>
               <IntituleAnomalie>Erreur de séquence</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>90110-146</CodeAnomalie>
               <IntituleAnomalie>Non admis</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
     </FunctionalBlock>
     <FunctionalBlock>
          <Code>90109</Code>
          <Version>2022/3</Version>
          <DatePublication>30/08/2022</DatePublication>
          <Nom>Déduction occupation</Nom>
          <Zones>00086 - CODE DÉDUCTION</Zones>
          <Zones>00088 - BASE DE CALCUL DE LA DÉDUCTION</Zones>
          <Zones>00089 - MONTANT DE LA DÉDUCTION</Zones>
          <Zones>00090 - DATE DE DÉBUT DU DROIT À LA DÉDUCTION</Zones>
          <Zones>00091 - NOMBRE DE MOIS FRAIS DE GESTION SSA</Zones>
          <Zones>00092 - NUMÉRO D'IDENTIFICATION DE LA SÉCURITÉ SOCIALE - NISS DE LA PERSONNE
               REMPLACÉE</Zones>
          <Zones>00093 - NUMÉRO D'IDENTIFICATION DE LA SÉCURITÉ SOCIALE - NISS DE LA PERSONNE QUI A
               OUVERT LE DROIT À LA DÉDUCTION</Zones>
          <Zones>00094 - ORIGINE DE L'ATTESTATION</Zones>
          <XmlLabel>OccupationDeduction</XmlLabel>
          <Description>Bloc fonctionnel permettant de déclarer les déductions demandées pour une
               occupation.</Description>
          <CardinaliteMinimum>0</CardinaliteMinimum>
          <CardinaliteMaximum>*</CardinaliteMaximum>
          <NrBlocLie>90250</NrBlocLie>
          <BlocLie>90250 - Détail données déduction occupation</BlocLie>
          <Presence>Cardinalité 0 si aucune déduction occupation n'est demandée. Cardinalité 1 ... *
               si la ligne travailleur concerne un code travailleur cotisation ordinaire (voir
               annexe 2) et qu'une déduction occupation (voir annexe 4) est demandée.</Presence>
          <LimitationsSupplementaires>Une déduction occupation donnée (un code déduction) ne peut se
               retrouver qu'une seule fois par occupation.</LimitationsSupplementaires>
          <Anomalie>
               <CodeAnomalie>90109-006</CodeAnomalie>
               <IntituleAnomalie>Trop d'occurrences avec les mêmes identifiants</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>90109-091</CodeAnomalie>
               <IntituleAnomalie>Erreur de séquence</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>90109-146</CodeAnomalie>
               <IntituleAnomalie>Non admis</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
     </FunctionalBlock>
     <FunctionalBlock>
          <Code>90108</Code>
          <Version>2022/3</Version>
          <DatePublication>30/08/2022</DatePublication>
          <Nom>Détail données déduction ligne travailleur</Nom>
          <Zones>00138 - NUMÉRO DE SUITE DÉTAIL DÉDUCTION</Zones>
          <Zones>00141 - MONTANT DE LA DÉDUCTION - DÉTAIL</Zones>
          <Zones>00142 - NUMÉRO D'ENREGISTREMENT DU RÈGLEMENT DE TRAVAIL</Zones>
          <Zones>00143 - DATE D'ORIGINE DU DROIT</Zones>
          <Zones>00147 - TEMPS DE TRAVAIL HEBDOMADAIRE MOYEN AVANT LA RÉDUCTION DU TEMPS DE TRAVAIL</Zones>
          <Zones>00148 - TEMPS DE TRAVAIL HEBDOMADAIRE MOYEN APRÈS LA RÉDUCTION DU TEMPS DE TRAVAIL</Zones>
          <XmlLabel>DeductionDetail</XmlLabel>
          <Description>Bloc fonctionnel permettant de déclarer les données détaillées pour certaines
               déductions ligne travailleur (cf. Annexe dmfas02).</Description>
          <CardinaliteMinimum>0</CardinaliteMinimum>
          <CardinaliteMaximum>99</CardinaliteMaximum>
          <NrBlocLie></NrBlocLie>
          <BlocLie></BlocLie>
          <Presence>Cardinalité 0 si la déduction ligne travailleur demandée ne nécessite aucun
               détail données déduction ligne travailleur (voir annexe dmfas02). Cardinalité 1 ...
               99 si la déduction ligne travailleur demandée nécessite un détail données déductions
               ligne travailleur (voir annexe dmfas02).</Presence>
          <LimitationsSupplementaires></LimitationsSupplementaires>
          <Anomalie>
               <CodeAnomalie>90108-006</CodeAnomalie>
               <IntituleAnomalie>Trop d'occurrences avec les mêmes identifiants</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>90108-091</CodeAnomalie>
               <IntituleAnomalie>Erreur de séquence</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>90108-146</CodeAnomalie>
               <IntituleAnomalie>Non admis</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
     </FunctionalBlock>
     <FunctionalBlock>
          <Code>90250</Code>
          <Version>2022/3</Version>
          <DatePublication>30/08/2022</DatePublication>
          <Nom>Détail données déduction occupation</Nom>
          <Zones>00138 - NUMÉRO DE SUITE DÉTAIL DÉDUCTION</Zones>
          <Zones>00143 - DATE D'ORIGINE DU DROIT</Zones>
          <Zones>00914 - DATE D'EXPIRATION DU DROIT</Zones>
          <Zones>00147 - TEMPS DE TRAVAIL HEBDOMADAIRE MOYEN AVANT LA RÉDUCTION DU TEMPS DE TRAVAIL</Zones>
          <Zones>00148 - TEMPS DE TRAVAIL HEBDOMADAIRE MOYEN APRÈS LA RÉDUCTION DU TEMPS DE TRAVAIL</Zones>
          <XmlLabel>OccupationDeductionDetail</XmlLabel>